highlighter: pygments
paginate: 10
markdown: kramdown
host: 0.0.0.0

subscribe_rss: /atom.xml
kramdown:
  input: GFM
  hard_wrap: false

home_url: "http://spoqa.github.io"
representing_image: "/images/og-logo.png"

sass:
    sass_dir: css
